# Generated by Django 4.0.3 on 2022-03-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('month', models.CharField(blank=True, db_column='Month', max_length=3, null=True)),
                ('district_name', models.CharField(blank=True, db_column='District_name', max_length=16, null=True)),
                ('sales', models.IntegerField(blank=True, db_column='Sales', null=True)),
            ],
            options={
                'db_table': 'dummy',
                'managed': False,
            },
        ),
    ]
