# Generated by Django 4.1.3 on 2023-08-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_city_alter_employee_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
